### ISSUE TITLE
Great project. License is missing.

### ISSUE THREAD

**Issue by amotl** [stefangrotz/OpenDataGermanyGPT#5]
Dear Stefan,

this is a sweet project you are conceiving here, kudos. I also stumbled upon two other gems in the same area [^1][^2], and intend to pair them in one way or another and make the result available through a package on PyPI, to make it reusable by others. In this spirit, may I humbly ask you to add a license file to your project, when appropriate, and if you like that idea?

With kind regards,
Andreas.

[^1]: https://github.com/mommi84/rdf-qa
[^2]: https://github.com/sdsc-ordes/kg-llm-interface

**Comment by stefangrotz** [comment]
Good remark. I will add a MIT or CC0 license later.

**Comment by amotl** [comment]
Thank you Stefan. 🙇

MIT would be excellent [^1], because CC0 isn't actually an open source software license, according to the designated list at https://opensource.org/licenses/.

[^1]: Or any other...

**Comment by stefangrotz** [comment]
Okay, done

**Comment by amotl** [comment]
Excellent, thank you.
